feature(Newsletter): Send quarterly newsletters to users
wri/fti_api pull request #337
Opened 2022-09-25 17:52 UTC by santostiago

Adds a job that sends quarterly newsletters to the users of a producer with information about the changing of scores and documents to expire.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
No email

Issue Number: https://www.pivotaltracker.com/story/show/181285357

## What is the new behavior?
With email!!! Yey!!

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-11-07 10:54 UTC, tsubik commented on app/services/mail_service.rb
> +    last_score = operator.score_operator_documents.at_date(Date.today - 3.months).last
`order(:date)` as order is never guaranteed, better to make sure it's good.

2022-11-07 10:54 UTC, tsubik commented on app/services/mail_service.rb
> +    text_en = ["Your current score is #{current_score.all}."]
As score is a percentage of valid documents provided and I'm not sure if anyway is accustomed to its raw full value. We need to make sure scores are properly formatted as percentage, with up to 2 digits after decimal points. What do you think? Is the text already approved by Sophie?

2022-11-07 10:54 UTC, tsubik commented on lib/tasks/scheduler.rake
> +    time = Benchmark.ms {  Operator.active.fa_operator.find_each { MailService.new.quarterly_newsletter(_1).deliver } }
First time I see `_1` in usage and TBH I have mixed feelings about it, maybe because first time I see it.

2022-11-07 11:01 UTC, tsubik commented on lib/tasks/scheduler.rake
> +    time = Benchmark.ms {  Operator.active.fa_operator.find_each { MailService.new.quarterly_newsletter(_1).deliver } }
There could be a problem with sending emails in this way. We have to migrate to sidekiq or any other background job and send each email in separate job as here if anything goes wrong with one operator then no emails will be sent to the rest. You could add a rescue here and keep sending to the last email and after that fail the whole task to inform us that something was wrong. That would be better but not ideal in my opinion.

2022-11-07 21:34 UTC, santostiago commented on app/services/mail_service.rb
> +    text_en = ["Your current score is #{current_score.all}."]
@tsubik right!
It will look better that way.

2022-11-07 21:37 UTC, santostiago commented on lib/tasks/scheduler.rake
> +    time = Benchmark.ms {  Operator.active.fa_operator.find_each { MailService.new.quarterly_newsletter(_1).deliver } }
@tsubik `_1` is the "recommended" way to use it now when the name of the block parameter is irrelevant. But probably here I can use `with_self` or similar.
True. It's definitely better to rescue it in case something goes wrong the other emails get sent (and we get logs letting us know something is wrong). Another thing worth checking is a service for error monitoring: we didn't add any, right?

2022-11-08 08:04 UTC, tsubik commented on lib/tasks/scheduler.rake
> +    time = Benchmark.ms {  Operator.active.fa_operator.find_each { MailService.new.quarterly_newsletter(_1).deliver } }
Ok. I added service to monitoring cron jobs (healthchecks.io) and sentry is for error monitoring as well.

2022-11-14 10:34 UTC, tsubik approved these changes
Approving, but still, I would add rescue in the block in the rake task when sending messages and manually report to sentry and fail the job after the rest is sent (or not sent).

2022-11-14 20:11 UTC, santostiago commented
@tsubik I haven't updated the PR to notify Sentry yet. I'll do it and re-request the review.

2022-11-20 12:53 UTC, santostiago commented
@tsubik I just updated it to notify sentry on error and proceed with the remaining operators.

2022-11-21 16:37 UTC, tsubik requested changes
Added a comment in rake task

2022-11-21 16:49 UTC, tsubik commented on app/services/mail_service.rb
> +    text_en = ["Your current score is #{current_score_percentage.all}."]
here and in the next line is `.all` to be removed.

2022-11-22 20:07 UTC, santostiago commented on app/services/mail_service.rb
> +    text_en = ["Your current score is #{current_score_percentage.all}."]
ups.

2022-11-22 20:25 UTC, tsubik commented on lib/tasks/scheduler.rake
> +    Rails.logger.info "Sent quarterly newsletters to operators. It took #{time} ms."
What do you think?

2022-11-23 10:15 UTC, tsubik approved these changes
I left a question if you think it would be beneficial to fail rake task at the end if there is any error, but other than that all good :+1:

2022-11-23 20:56 UTC, santostiago commented
@tsubik do we get any particular notification if the rake task fails?
Isn't it enough to notify Sentry for each error?

2022-11-24 12:51 UTC, tsubik commented
Yes we do have healtchecks for cronjobs, better to add it, if Sentry somehow fails then we will have a fail in other place.

2022-11-24 12:54 UTC, merged