importer(Documents): Import Generic Operator Documents
wri/fti_api pull request #361
Opened 2022-11-12 16:15 UTC by santostiago

[Task](https://www.pivotaltracker.com/story/show/181285797)

This commit adds a rake task to import the generic operator documents (documents that belong to no country and should be generated for particular operators that work in countries not included in OTP)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2022-11-14 11:47 UTC, tsubik commented on app/admin/operator_document.rb
> +             .where(country_translations: { locale: I18n.locale }).all.map { |x| ["#{x.name} - #{x.country&.name}", x.id] }
maybe we should add `display_name` property to the model, as with generic document we either want to not have `-` or have ` - Generic` suffix.

2022-11-14 11:54 UTC, tsubik commented on app/admin/operator_documents_dashboard.rb
> +        link_to resource.country.name, admin_country_path(resource.country) if resource.country.present?
This is not needed here as the `else` is already for `resource.country.present?`

2022-11-14 12:25 UTC, tsubik commented on app/admin/operator_document.rb
> +             .where(country_translations: { locale: I18n.locale }).all.map { |x| ["#{x.name} - #{x.country&.name}", x.id] }
Also that won't work as there is `inner join` in the scope and where on country_translations with specific locale. So it won't show generic documents in that list.

2022-11-14 12:26 UTC, tsubik commented on lib/tasks/data_import.rake
> +        rodg = RequiredOperatorDocumentGroup.find_by!(name: row['Legal category'])
Did you check it on production dump? It did not work, and I had to remove trailing spaces from 2 document categories. I did it on production and staging already.

2022-11-14 12:47 UTC, tsubik commented on lib/tasks/data_import.rake
> +        rodg = RequiredOperatorDocumentGroup.find_by!(name: row['Legal category'])
Documents were created only for handful (9 exactly) non active operators.

2022-11-14 12:48 UTC, tsubik requested changes
Couple changes are necessary with filters and creation of documents, on which I guess the decision is still pending.

2022-11-14 20:29 UTC, santostiago commented on app/admin/operator_document.rb
> +             .where(country_translations: { locale: I18n.locale }).all.map { |x| ["#{x.name} - #{x.country&.name}", x.id] }
> Also that won't work as there is `inner join` in the scope and where on country_translations with specific locale. So it won't show generic documents in that list.

@tsubik I think we talked about this before: don't the translations get generated when the models are saved (if the translations were null)? I thought that was the behavior.

2022-11-14 20:29 UTC, santostiago commented on app/admin/operator_documents_dashboard.rb
> +        link_to resource.country.name, admin_country_path(resource.country) if resource.country.present?
Ups... missed that one.

2022-11-14 20:30 UTC, santostiago commented on lib/tasks/data_import.rake
> +        rodg = RequiredOperatorDocumentGroup.find_by!(name: row['Legal category'])
@tsubik I'm going to check the generation of documents again. They shouldn't be generated for anyone.

2022-11-15 12:10 UTC, tsubik commented on app/admin/operator_document.rb
> +             .where(country_translations: { locale: I18n.locale }).all.map { |x| ["#{x.name} - #{x.country&.name}", x.id] }
Yes, but here is other problem. Now,  the new Required operator document won't have country and you are using `inner join` + where in that joined translation table, please change it to make sure new required operator document will also be on the list, but with better names. Could be just without country name and "-" sign.

2022-11-17 20:37 UTC, santostiago commented on app/admin/operator_documents_dashboard.rb
> +        link_to resource.country.name, admin_country_path(resource.country) if resource.country.present?
I don't know why I did this..

2022-11-19 18:02 UTC, santostiago commented on lib/tasks/data_import.rake
> +        rodg = RequiredOperatorDocumentGroup.find_by!(name: row['Legal category'])
So, the rule is to do the same as for other ROD when they're added.

2022-11-19 22:08 UTC, santostiago commented on app/admin/operator_document.rb
> +             .where(country_translations: { locale: I18n.locale }).all.map { |x| ["#{x.name} - #{x.country&.name}", x.id] }
`display_name` on the model would require a query to fetch the country translation per each ROD.
I ended up doing it all in sql.

2022-11-21 15:16 UTC, tsubik commented on app/models/required_operator_document_fmu.rb
> +    return Fmu.where.not(country_id: Country.active.uniq.pluck(:id)) if country_id.blank?
I think `not(country: Country.active)` would have the same result in generated AR queries (but I'm not sure) - plus is that would be more readable.

2022-11-21 15:22 UTC, tsubik commented on app/models/required_operator_document_fmu.rb
> +    return Fmu.where.not(country_id: Country.active.uniq.pluck(:id)) if country_id.blank?
but I don't understand this line.

2022-11-21 15:23 UTC, tsubik commented on app/models/required_operator_document_fmu.rb
> +    return Fmu.where.not(country_id: Country.active.uniq.pluck(:id)) if country_id.blank?
If `country_id` is blank then the document is for all non active countries fmus? Why?

2022-11-21 15:29 UTC, tsubik commented on app/models/required_operator_document_fmu.rb
> +    return Fmu.where.not(country_id: Country.active.uniq.pluck(:id)) if country_id.blank?
actually queries will be different, with `country: Country.active` there will be only one query.

2022-11-21 15:34 UTC, tsubik commented on lib/tasks/data_import.rake
> +        rodg = RequiredOperatorDocumentGroup.find_by!(name: row['Legal category'])
Works on the dump now, and no documents were created.

2022-11-22 20:00 UTC, santostiago commented on app/models/required_operator_document_fmu.rb
> +    return Fmu.where.not(country_id: Country.active.uniq.pluck(:id)) if country_id.blank?
> If country_id is blank then the document is for all non active countries fmus? Why?

@tsubik that's the rule.
When we create a generic ROD (whether they're for countries or FMUs), they are required for countries/fmus that are not in the list of active countries.
Active countries have a proper list of ROD. All the other ones have this generic list (which is shorter and "generic)

2022-11-22 20:01 UTC, santostiago commented on lib/tasks/data_import.rake
> +        rodg = RequiredOperatorDocumentGroup.find_by!(name: row['Legal category'])
@tsubik yes. There are no operators in other countries that have an `fa_id`.
This will have to be changed by Sophie.

2022-11-22 20:30 UTC, tsubik commented on app/models/required_operator_document_fmu.rb
> +    return Fmu.where.not(country_id: Country.active.uniq.pluck(:id)) if country_id.blank?
Ohh, ok, now that's clear.

2022-11-22 20:35 UTC, tsubik commented on app/models/required_operator_document_fmu.rb
> +    return Fmu.where.not(country_id: Country.active) if country_id.blank?
Ok, now it's clear for me that generic are also for fmu documents for non active countries. So, `RequiredOperatorDocumentFmu` is generic if it does not have country_id, right? Maybe we can add method

```
def generic?
  country_id.blank?
end
```
and this code would be clear at first sight.
```

2022-11-23 11:09 UTC, tsubik approved these changes
:+1:

2022-11-24 12:44 UTC, merged