Feat add positions to required documents
wri/fti_api pull request #362
Opened 2022-11-13 11:45 UTC by santostiago

[Task](https://www.pivotaltracker.com/story/show/181285845)

Adds the field `position` to `RequiredOperatorDocument` and `RequiredGovDocument` that should be unique within the `Country` and the `RequiredDocumentGroup`.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://www.pivotaltracker.com/story/show/181285845

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-11-14 11:34 UTC, tsubik requested changes
I think we should use acts_as_list

2022-11-14 11:34 UTC, tsubik commented on app/models/required_gov_document.rb
> +  validates :position, uniqueness: { scope: %w[country_id required_gov_document_group_id] }, allow_nil: true
can we use `acts_as_list` instead? We are already using it in about page entries. I think I added that there to have better UX for the user (no need to manually add priority or changing priority will change the rest).

2022-11-14 11:34 UTC, tsubik commented on spec/models/required_operator_document_spec.rb
> +    describe '#validate_position' do
no need for this if we use `acts_as_list`

2022-11-20 13:25 UTC, santostiago commented
@tsubik `acts_as_list` is gonna be messy for these models.
Because it enforces uniqueness within a scope, when we delete required documents, there are going to be collisions of the positions and we'll have to hack around it, making it more complicated than it should.
WDYT?

2022-11-20 19:37 UTC, santostiago commented
@tsubik added `acts_as_list`.

2022-11-21 11:50 UTC, tsubik commented on db/migrate/20221112185114_add_position_to_documents.rb
> +        rgd.update_column(:position, index + 1)
Ohh, not sure if that is a good idea. Right now on the frontend I sort by first position then name, as sorting by name was by default on the frontend. If you update position to be sorted by created_at date then the whole order will be different. You should order by name.

2022-11-21 12:23 UTC, tsubik requested changes
@santostiago please add `position` attribute to jsonapi resources.

2022-11-21 12:33 UTC, tsubik commented
You can test this PR with current `develop` version of otp portal, or staging.

2022-11-21 12:36 UTC, tsubik commented on db/migrate/20221112185114_add_position_to_documents.rb
> +        rgd.update_column(:position, index + 1)
Keeping position as `null` would also work on frontend, as if position is null then frontend sort the rest by title.

2022-11-22 18:33 UTC, santostiago commented on db/migrate/20221112185114_add_position_to_documents.rb
> +        rgd.update_column(:position, index + 1)
@tsubik ok, I'll change it to be ordered by name.

2022-11-22 19:34 UTC, santostiago commented on db/migrate/20221112185114_add_position_to_documents.rb
> +        rgd.update_column(:position, index + 1)
@tsubik and this is from `acts_as_list` documentation:
> As it stands acts_as_list requires position values to be set on the model before the instance methods above will work. Adding something like the below to your migration will set the default position. Change the parameters to order if you want a different initial ordering.

2022-11-22 19:36 UTC, santostiago commented on db/migrate/20221112185114_add_position_to_documents.rb
> +        rgd.update_column(:position, index + 1)
(I mean, we don't really need those methods, but it's better to have everything ordered instead of requiring them to add a position for all)

2022-11-22 19:45 UTC, tsubik commented
I tried it and you don't have to set position, could be null and it worked
fine as well, but we can set it if it's not too hard.

On Tue, Nov 22, 2022, 20:36 Tiago Santos ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In db/migrate/20221112185114_add_position_to_documents.rb
> <https://github.com/wri/fti_api/pull/362#discussion_r1029748635>:
>
> > @@ -0,0 +1,36 @@
> +class AddPositionToDocuments < ActiveRecord::Migration[5.1]
> +  def change
> +    add_column :required_operator_documents, :position, :integer
> +    add_column :required_gov_documents, :position, :integer
> +
> +    RequiredOperatorDocument.group(:country_id).pluck(:country_id).each do |country_id|
> +      RequiredOperatorDocument.where(country_id: country_id).order(:created_at).each.with_index do |rod, index|
> +        rod.update_column(:position, index)
> +      end
> +    end
> +
> +    RequiredGovDocument.group(:country_id).pluck(:country_id).each do |country_id|
> +      RequiredGovDocument.where(country_id: country_id).order(:created_at).each.with_index do |rgd, index|
> +        rgd.update_column(:position, index + 1)
>
> (I mean, we don't really need those methods, but it's better to have
> everything ordered instead of requiring them to add a position for all)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wri/fti_api/pull/362#discussion_r1029748635>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ2CLAK7NI5QJ3RZIAHGTLWJUODJANCNFSM6AAAAAAR67KKKY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-22 19:49 UTC, santostiago commented
@tsubik ready.
(I didn't understand the testing part)

2022-11-22 20:38 UTC, tsubik commented
I meant, frontend changes are already deployed, so you can test it locally with otp portal.

2022-11-23 20:52 UTC, santostiago commented
@tsubik added the sorting to consider the RODG.
Checked it on the BO, but I'll configure the portal tomorrow.

2022-11-24 11:05 UTC, tsubik approved these changes
:+1:

2022-11-24 12:46 UTC, merged