feat(Operator) Remove translations
wri/fti_api pull request #419
Opened 2023-02-12 21:11 UTC by santostiago

Remove the translations and moves it to the Operator.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://www.pivotaltracker.com/story/show/183775139

2023-02-13 16:10 UTC, tsubik requested changes
@santostiago I don't see migration code here

2023-02-19 16:52 UTC, santostiago commented on app/models/operator.rb
> -      if saved_change_to_name? && locale == :en
> @santostiago I don't see migration code here

I just noted it was not added to the commit 😨 
Adding it now.

2023-02-19 17:29 UTC, santostiago commented on app/models/operator.rb
> -      if saved_change_to_name? && locale == :en
>this hook was to update fmu geojson properties with new operator's name, so you have to re-add this hook to operator model.
Done.

2023-02-20 13:31 UTC, tsubik approved these changes
Looks great :+1:

2023-03-03 09:18 UTC, merged