Feat(Observations): Add automatic translations
wri/fti_api pull request #481
Opened 2024-01-15 19:37 UTC by santostiago

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-01-29 21:33 UTC, santostiago commented
@tsubik I'll add the specs during the week, but the code should be close to what it is now.

2024-01-30 15:31 UTC, tsubik reviewed
Cannot run `bundle install`. There is some problem with `googleauth (1.9.0)`, not sure why. Quick fix is to just run `bundle update google-cloud-translate`.

2024-01-30 16:05 UTC, tsubik reviewed
Looks really good. I still need to test it locally after setting up google cloud. For now, I'm adding a couple comments. Also, this needs rebasing (that would fix security workflow).

2024-01-30 16:05 UTC, tsubik commented on app/jobs/translation_job.rb
> +        translated_fields[field][locale] = translation_service.run(entity.send(field), original_locale, locale)
Only this line could be within block of `I18n.with_locale(original_locale)`. Instead of changing locale globally couple lines above. I think that could be more clear what is going on here.

2024-01-30 16:05 UTC, tsubik commented on db/migrate/20240128163512_add_automatic_translation_field_to_observation_translations.rb
> +    add_column :observation_translations, :details_translated_from, :string
All columns are translated at once, couldn't we have only one column like `auto_translated_from`?

2024-01-30 16:48 UTC, tsubik commented on app/admin/observation.rb
> +        link_to I18n.t("active_admin.observations_page.force_translations"), force_translations_admin_observation_path(resource), method: :put, class: 'button'
There is also problem that user using English in backend interface, but is changing something in French and wants to force translation from French not English.

2024-02-02 13:15 UTC, santostiago commented on app/resources/v1/observation_resource.rb
> +      @model.admin_locale = user.locale
Right!

2024-02-02 13:16 UTC, santostiago commented on app/jobs/translation_job.rb
> +        I18n.locale = locale
You mean the block? Yeah, can be.

2024-02-02 13:18 UTC, santostiago commented on db/migrate/20240128163512_add_automatic_translation_field_to_observation_translations.rb
> +    add_column :observation_translations, :details_translated_from, :string
I thought of it, but maybe we'd like to change this to translate just one attribute, and it would be nice to know which one.

2024-02-02 13:19 UTC, santostiago commented on app/admin/observation.rb
> +        link_to I18n.t("active_admin.observations_page.force_translations"), force_translations_admin_observation_path(resource), method: :put, class: 'button'
Mmmm.. from the conversation with Sophie I understood she'd like to have a button to make the translation, instead of saving the whole form.

2024-02-02 13:27 UTC, santostiago commented on app/resources/v1/observation_resource.rb
> +      @model.admin_locale = user.locale
In fact, we have a lot of observations without `modfied_user`.

2024-02-06 09:29 UTC, tsubik commented on app/resources/v1/observation_resource.rb
> +      @model.admin_locale = user.locale
Maybe those are old ones or were imported at the beginning?

2024-02-06 09:29 UTC, tsubik commented on app/jobs/translation_job.rb
> +        I18n.locale = locale
Yes, the block.

2024-02-06 09:30 UTC, tsubik commented on db/migrate/20240128163512_add_automatic_translation_field_to_observation_translations.rb
> +    add_column :observation_translations, :details_translated_from, :string
Sure, I thought that could be the reason.

2024-02-27 17:32 UTC, tsubik commented on .env.sample
> +GOOGLE_CLIENT_ID=
looks like only API_KEY is used, so this could be removed.

2024-03-23 14:25 UTC, santostiago commented
@tsubik I added a new field on the edit form containing the language to translate from. When something is selected, when submitting the form, the translation will occur based on the selected language.
I also added a way to directly translate the field on the view page.

2024-03-23 14:25 UTC, santostiago commented
It seems like all the tests are failing... maybe I should rebase from master.

2024-03-25 19:39 UTC, tsubik requested changes
I like the new way of forcing translations, but I have some errors with translating job. Not sure what is the problem (some invalid argument error coming from google translate), will check it again tomorrow (maybe something changed in gem version as I have to `bundle update google-cloud-translate` to even run this code). I left some other comments though.

2024-03-25 19:39 UTC, tsubik commented on app/admin/observation.rb
> +      div do
The input looks weird, but if you remove that `div` it looks a way better, not sure why that div is here?

2024-03-25 19:39 UTC, tsubik commented on app/admin/observation.rb
> +        f.input :admin_locale, label:  I18n.t("active_admin.observations_page.translate_from"),
I like it that it's only select input without the button to force translation.

2024-03-25 19:39 UTC, tsubik commented on app/admin/observation.rb
> +        f.input :admin_locale, label:  I18n.t("active_admin.observations_page.translate_from"),
I would hide it when observation is not `published`, as I see in that case force translation is not working. I would also add some hint message saying something about how it works.

2024-03-26 07:44 UTC, tsubik commented on app/admin/observation.rb
> +        f.input :admin_locale, label:  I18n.t("active_admin.observations_page.translate_from"),
Hint message like: "Set if you want to perform automatic translations of all texts from selected language"

2024-03-26 07:57 UTC, tsubik commented on app/jobs/translation_job.rb
> +        next if locale == original_locale
Ok, I found what is the problem. It still tries to do translations like from "fr" to "fr" as when forcing translations `original_locale` is string and available_locales symbol, needs to be normalized.

2024-03-26 07:59 UTC, tsubik commented on app/models/observation.rb
> +  attr_accessor :admin_locale
I would probably change that name to `force_translations_from` or similar.

2024-04-08 17:54 UTC, tsubik reviewed
Just found some minor things, probably naming typos. Otherwise, force translations feature works great.

2024-04-08 17:54 UTC, tsubik commented on app/admin/observation.rb
> +    translate_to = params[:translate_to] || I18n.locale
Hmm, shouldn't that be `translate_from`?

2024-04-08 17:54 UTC, tsubik commented on app/admin/observation.rb
> +    dropdown_menu I18n.t("active_admin.observations_page.force_translations") do
Nice.

2024-04-08 17:54 UTC, tsubik commented on app/admin/observation.rb
> +        item locale, force_translations_admin_observation_path(observation, translate_to: locale)
same, should probably be `translate_from`.

2024-05-09 08:21 UTC, tsubik approved these changes
LGTM :+1:

2024-05-12 09:15 UTC, merged